// KOL wallets listed on kolscan.io's leaderboard (name, X handle, Solana address): the ~200 most
// active of a public snapshot of it (github.com/nirholas/kol-quest, scraped 2026-04-09; daily
// leaderboard traders first, then weekly). KOLs change wallets: the tracker checks each one's
// activity on chain and by default follows only those that traded in the last 7 days.
export const KOLS = [
  { name: "Exotic", twitter: "74Exotic", wallet: "Dwo2kj88YYhwcFJiybTjXezR9a6QjkMASz5xXD7kujXC" },
  { name: "chester", twitter: "Chestererer", wallet: "PMJA8UQDyWTFw2Smhyp9jGA6aTaP7jKHR7BPudrgyYN" },
  { name: "Flames", twitter: "FlamesOnSol", wallet: "6aXFYXbFob1ZKAEDCcqZnX2vooA3TgEqDoy5dAQbeWoV" },
  { name: "decu", twitter: "notdecu", wallet: "4vw54BmAogeRV3vPKWyFet5yf8DTLcREzdSzx4rw9Ud9" },
  { name: "dv", twitter: "vibed333", wallet: "BCagckXeMChUKrHEd6fKFA1uiWDtcmCXMsqaheLiUPJd" },
  { name: "Kev", twitter: "Kevsznx", wallet: "BTf4A2exGK9BCVDNzy65b9dUzXgMqB4weVkvTMFQsadd" },
  { name: "k4ye", twitter: "k4yeSol", wallet: "5fHJszey2UdB2nETS1y6NS2wSG4ic9byKtbgJzaYzGeV" },
  { name: "Kadenox", twitter: "kadenox", wallet: "B32QbbdDAyhvUQzjcaM5j6ZVKwjCxAwGH5Xgvb9SJqnC" },
  { name: "Sheep", twitter: "imsheepsol", wallet: "78N177fzNJpp8pG49xDv1efYcTMSzo9tPTKEA9mAVkh2" },
  { name: "CameXBT", twitter: "Camexbt", wallet: "67SNjkjV2MEyhDZcDjvMQSqFtjkh6TjCq6KDLmCgUxx6" },
  { name: "Fashr", twitter: "FASHRCrypto", wallet: "719sfKUjiMThumTt2u39VMGn612BZyCcwbM5Pe8SqFYz" },
  { name: "M A M B A 🧲", twitter: "mambatrades_", wallet: "4nvNc7dDEqKKLM4Sr9Kgk3t1of6f8G66kT64VoC95LYh" },
  { name: "Silver", twitter: "0xSilver", wallet: "67Nwfi9hgwqhxGoovT2JGLU67uxfomLwQAWncjXXzU6U" },
  { name: "Clown", twitter: "ClownsTrenches", wallet: "EDXHdSFdadFbYFFjxPXBqMe1kCEDFqpPu552uvp48HR8" },
  { name: "Daumen", twitter: "daumenxyz", wallet: "8MaVa9kdt3NW4Q5HyNAm1X5LbR8PQRVDc1W8NMVK88D5" },
  { name: "Earl", twitter: "earlTrades", wallet: "F2SuErm4MviWJ2HzKXk2nuzBC6xe883CFWUDCPz6cyWm" },
  { name: "Gasp", twitter: "oh_gasp", wallet: "xyzfhxfy8NhfeNG3Um3WaUvFXzNuHkrhrZMD8dsStB6" },
  { name: "noob mini", twitter: "noobmini_", wallet: "AGqjivJr1dSv73TVUvdtqAwogzmThzvYMVXjGWg2FYLm" },
  { name: "Orange", twitter: "OrangeSBS", wallet: "2X4H5Y9C4Fy6Pf3wpq8Q4gMvLcWvfrrwDv2bdR8AAwQv" },
  { name: "Letterbomb", twitter: "ihateoop", wallet: "BtMBMPkoNbnLF9Xn552guQq528KKXcsNBNNBre3oaQtr" },
  { name: "AlxCooks", twitter: "AlxCooks_off", wallet: "89HbgWduLwoxcofWpmn1EiF9wEdpgkNDEyPjzZ72mkDi" },
  { name: "Casino", twitter: "casino616", wallet: "8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR" },
  { name: "Zuki", twitter: "zukiweb3", wallet: "922VvmmYDHV9KMTJJ71Y5Yd3Vn7cfJuFasLNSsZPygrG" },
  { name: "Mazino", twitter: "Mazinotrenches", wallet: "9r1BenK1nPvkZyD88q3e6bTKjfqDcLjxnXn9ovreDL52" },
  { name: "Files", twitter: "xfilesboy", wallet: "DtjYbZntc2mEm1UrZHNcKguak6h6QM4S5xobnwFgg92Y" },
  { name: "ozark", twitter: "ohzarke", wallet: "DZAa55HwXgv5hStwaTEJGXZz1DhHejvpb7Yr762urXam" },
  { name: "Otta", twitter: "ottabag", wallet: "As7HjL7dzzvbRbaD3WCun47robib2kmAKRXMvjHkSMB5" },
  { name: "WaiterG", twitter: "Waiter1x", wallet: "4cXnf2z85UiZ5cyKsPMEULq1yufAtpkatmX4j4DBZqj2" },
  { name: "Lowskii (believes)", twitter: "Lowskii_gg", wallet: "41uh7g1DxYaYXdtjBiYCHcgBniV9Wx57b7HU7RXmx1Gg" },
  { name: "Veloce", twitter: "VeloceSVJ", wallet: "2W14ahXD3XBfWJchQ4K5NLXmguWWcTTUTuHDhEzeuvP3" },
  { name: "danny", twitter: "cladzsol", wallet: "EaVboaPxFCYanjoNWdkxTbPvt57nhXGu5i6m9m6ZS2kK" },
  { name: "Henn", twitter: "henn100x", wallet: "FRbUNvGxYNC1eFngpn7AD3f14aKKTJVC6zSMtvj2dyCS" },
  { name: "Dani", twitter: "DaniWorldwide", wallet: "AuPp4YTMTyqxYXQnHc5KUc6pUuCSsHQpBJhgnD45yqrf" },
  { name: "xander", twitter: "xandereef", wallet: "B3wagQZiZU2hKa5pUCj6rrdhWsX3Q6WfTTnki9PjwzMh" },
  { name: "Nilla", twitter: "NillaGurilla", wallet: "j38fhfqWsJyt8hzym48P8QMsXWx1FfLUxQwuor7Ti4o" },
  { name: "Schoen", twitter: "Schoen_xyz", wallet: "5hAgYC8TJCcEZV7LTXAzkTrm7YL29YXyQQJPCNrG84zM" },
  { name: "Tuults", twitter: "tuults69", wallet: "5T229oePmJGE5Cefys8jE9Jq8C7qfGNNWy3RVA7SmwEP" },
  { name: "Bluey", twitter: "Blueycryp", wallet: "6TAHDM5Tod7dBTZdYQxzgJZKxxPfiNV9udPHMiUNumyK" },
  { name: "Sanity", twitter: "Sanity100x", wallet: "5ruP877fu8sBshx9inDeHsVLjnJtgVBTbjnbupeDHYHH" },
  { name: "Padre", twitter: "PadrePrints", wallet: "4Ff9dbi9L93qMvevpESY4YLHtdqTd8Yj8jXj3VwCNY4g" },
  { name: "EustazZ", twitter: "Eustazzeus", wallet: "FqamE7xrahg7FEWoByrx1o8SeyHt44rpmE6ZQfT7zrve" },
  { name: "Sebastian", twitter: "Saint_pablo123", wallet: "3BLjRcxWGtR7WRshJ3hL25U3RjWr5Ud98wMcczQqk4Ei" },
  { name: "Giann", twitter: "Giann2K", wallet: "GNrmKZCxYyNiSUsjduwwPJzhed3LATjciiKVuSGrsHEC" },
  { name: "Tom", twitter: "tdmilky", wallet: "CEUA7zVoDRqRYoeHTP58UHU6TR8yvtVbeLrX1dppqoXJ" },
  { name: "Banf", twitter: "BanfSol", wallet: "Fv8byBKV8jK8jxoUtgB1A1dqGcxSoN8x7bUZobP8Xn1d" },
  { name: "Megga", twitter: "Megga", wallet: "H31vEBxSJk1nQdUN11qZgZyhScyShhscKhvhZZU3dQoU" },
  { name: "kreo", twitter: "kreo444", wallet: "BCnqsPEtA1TkgednYEebRpkmwFRJDCjMQcKZMMtEdArc" },
  { name: "West", twitter: "ratwizardx", wallet: "JDd3hy3gQn2V982mi1zqhNqUw1GfV2UL6g76STojCJPN" },
  { name: "Publix", twitter: "Publixplayz", wallet: "86AEJExyjeNNgcp7GrAvCXTDicf5aGWgoERbXFiG1EdD" },
  { name: "Putrick", twitter: "Putrickk", wallet: "AVjEtg2ECYKXYeqdRQXvaaAZBjfTjYuSMTR4WLhKoeQN" },
  { name: "rez", twitter: "rezthegreatt", wallet: "FkRN9yF3Gysw3BVhUqAXJJMEGfKiJNaPQAWYWBErgDuN" },
  { name: "Leens", twitter: "leensx100", wallet: "LeenseyyUU3ccdBPCFCrrZ8oKU2B3T2uToGGZ7eVABY" },
  { name: "CoCo", twitter: "CoCoCookerr", wallet: "FqojC24nUn3x6oMQC2ypBHmtH7rFAnKS6DvwsJoCMaiv" },
  { name: "rambo", twitter: "goatedondsticks", wallet: "2net6etAtTe3Rbq2gKECmQwnzcKVXRaLcHy2Zy1iCiWz" },
  { name: "Red", twitter: "redwithbag", wallet: "7ABz8qEFZTHPkovMDsmQkm64DZWN5wRtU7LEtD2ShkQ6" },
  { name: "unprofitable", twitter: "exitliquid1ty", wallet: "DYmsQudNqJyyDvq86XmzAvrU9T7xwfQEwh6gPQw9TPNF" },
  { name: "fz7", twitter: "fz7", wallet: "G2mgnzpr59vYjKpwU9q5zVfS9yQ9HezMwjuqF7LACvR4" },
  { name: "crayohla", twitter: "CrayohlaEU", wallet: "GDoG4tdbx8qkpECQKF5MebbEDpFJn6H739psqgoTG3aN" },
  { name: "Betman", twitter: "ImTheBetman", wallet: "BoYHJoKntk3pjkaV8qFojEonSPWmWMfQocZTwDd1bcGG" },
  { name: "Monki", twitter: "m0nkicrypto", wallet: "53BnNc49Ajgstciq3CRoyxuBpkkW1r8pgPyvr7JGYnsh" },
  { name: "Scrim", twitter: "mircs", wallet: "GBERKNpahPnBGmeUGWQVjGBDBj6CcJKpGz34FqegmTgu" },
  { name: "marker", twitter: "m4rk3r", wallet: "CQervCdE3WAUGRmaTj9NHdbNrNGVsxJb68t3QggcntM2" },
  { name: "Scharo", twitter: "XScharo", wallet: "4sAUSQFdvWRBxR8UoLBYbw8CcXuwXWxnN8pXa4mtm5nU" },
  { name: "MACXBT", twitter: "00MACXBT", wallet: "ETU3GyrUsv6UztQJxHgsBX2UoJFmq79WJe3JyDpAqGMz" },
  { name: "King", twitter: "thekryptoking_", wallet: "69z4qTgQ5DBRTJvnQzx2h8jZhNsv5UgADotEwwKUm2JS" },
  { name: "jakey", twitter: "jakeyPRMR", wallet: "B3JyPD3t9ufZWfL3namyvoc258KH74JojSxxurUg9jCT" },
  { name: "JB", twitter: "JbTheQuant", wallet: "JBrYniqfp9ZVWdrkhMEX2LNGBpYJ673Tzh2m3XsS14p7" },
  { name: "Ducky", twitter: "zXDuckyXz", wallet: "ADC1QV9raLnGGDbnWdnsxazeZ4Tsiho4vrWadYswA2ph" },
  { name: "Matt", twitter: "MattFws", wallet: "3bzaJd5yZG73EVDz8xosQb7gfZm2LN5auFGh6wnP1n1f" },
  { name: "trunoest", twitter: "trunoest", wallet: "ardinRsN1mNYVeoJWTBsWeYeXvuR9UUDGMsCDKpb6AT" },
  { name: "storm", twitter: "stormtradez", wallet: "Dxudj2DQ5odnqgZvUocaeWc1eYC78Q8vfmVtPpvTrRNh" },
  { name: "Roshi 風と", twitter: "roshi100x", wallet: "5JrDgnED5QFiaE8Znny2S9GwCeDK2pLYjMfWmjKogs3w" },
  { name: "Jidn", twitter: "jidn_w", wallet: "3h65MmPZksoKKyEpEjnWU2Yk2iYT5oZDNitGy5cTaxoE" },
  { name: "bust", twitter: "IAmAboutToBust", wallet: "FzVQSzj8JJr6WMGqbUHzx2XH1KkrfxRrRPv6WcbbZmND" },
  { name: "shah", twitter: "shahh", wallet: "7xwDKXNG9dxMsBSCmiAThp7PyDaUXbm23irLr7iPeh7w" },
  { name: "Junior", twitter: "Junior_dot_", wallet: "3tnzEgqo6U19ocZbbc49vcGv3mGSoWNFAYjQQk5gF2qP" },
  { name: "Smokez", twitter: "SmokezXBT", wallet: "5t9xBNuDdGTGpjaPTx6hKd7sdRJbvtKS8Mhq6qVbo8Qz" },
  { name: "Bastille", twitter: "BastilleBtc", wallet: "3kebnKw7cPdSkLRfiMEALyZJGZ4wdiSRvmoN4rD1yPzV" },
  { name: "Lucas", twitter: "LockedInLucas", wallet: "6uwzmiSnR2vVwrh6EsQfuwSVk8ScqsfYkJPQQ2eydU2M" },
  { name: "Grimace", twitter: "naughtygrimace", wallet: "EA4MXkyF8C2NzY8fw2acJPuarmoU271KRCCAYpLzMBJr" },
  { name: "Kimba", twitter: "Kimbazxz", wallet: "7mHqL9GzGnbsYLoHLDzB7FiHAZbND2CZCJYFvU9PU1d3" },
  { name: "TIL", twitter: "tilcrypto", wallet: "EHg5YkU2SZBTvuT87rUsvxArGp3HLeye1fXaSDfuMyaf" },
  { name: "Zemrics", twitter: "Zemrics", wallet: "EP5mvfhGv6x1XR33Fd8eioiYjtRXAawafPmkz9xBpDvG" },
  { name: "Pavel", twitter: "pavelbtc", wallet: "3jckt69SiN3aCMbBWJoDS1s4xxGpqNxFFKnwhpRAQmuL" },
  { name: "Felix", twitter: "Felixonchain", wallet: "3uz65G8e463MA5FxcSu1rTUyWRtrRLRZYskKtEHHj7qn" },
  { name: "Reljoo", twitter: "Reljoooo", wallet: "FsG3BaPmRTdSrPaivbgJsFNCCa8cPfkUtk8VLWXkHpHP" },
  { name: "The Doc", twitter: "KayTheDoc", wallet: "DYAn4XpAkN5mhiXkRB7dGq4Jadnx6XYgu8L5b3WGhbrt" },
  { name: "Naruza", twitter: "0xNaruza", wallet: "ASVzakePP6GNg9r95d4LPZHJDMXun6L6E4um4pu5ybJk" },
  { name: "Coasty", twitter: "coasty_sol", wallet: "CATk62cYqDFXTh3rsRbS1ibCyzBeovc2KXpXEaxEg3nB" },
  { name: "BIGWARZ", twitter: "bigwarzeth", wallet: "7bsTkeWcSPG6nzsbXucxV89YUULoSExNJdX2WqfLHwZ4" },
  { name: "Dex", twitter: "igndex", wallet: "mW4PZB45isHmnjGkLpJvjKBzVS5NXzTJ8UDyug4gTsM" },
  { name: "Xanse.", twitter: "xansey", wallet: "B9K2wTQcRDLRLhMKFyRh2hPqHrr6VKiCC9yNGpkMUXrh" },
  { name: "Advyth", twitter: "Advyth", wallet: "GEKZWL474tFAyYDUoTgKEgYuMxT3Se7HzKDDptrnXnvS" },
  { name: "Absol", twitter: "absolquant", wallet: "BXNiM7pqt9Ld3b2Hc8iT3mA5bSwoe9CRrtkSUs15SLWN" },
  { name: "blixze ♱", twitter: "blixze", wallet: "5vg7he5HibvsAW86wfiuP6jw7VwKmUAnP6P93mVCdpJu" },
  { name: "Tally ꨄ︎", twitter: "tallxyyy", wallet: "JAmx4Wsh7cWXRzQuVt3TCKAyDfRm9HA7ztJa4f7RM8h9" },
  { name: "Groovy", twitter: "0xGroovy", wallet: "34ZEH778zL8ctkLwxxERLX5ZnUu6MuFyX9CWrs8kucMw" },
  { name: "samsrep", twitter: "samsrepx", wallet: "CUHBzSPSaNS3tArEtM3maSV6pNdJhHJFYZpurPPK9P7H" },
  { name: "Johnson", twitter: "johnsoncooks101", wallet: "J9TYAsWWidbrcZybmLSfrLzryANf4CgJBLdvwdGuC8MB" },
  { name: "racks", twitter: "rackstm_", wallet: "CM1dn5LZ21o6PQv3NQpQeEFPGGo9dNpSQ4eWQctmp17g" },
  { name: "Coler", twitter: "ColerCooks", wallet: "99xnE2zEFi8YhmKDaikc1EvH6ELTQJppnqUwMzmpLXrs" },
  { name: "S", twitter: "runitbackghost", wallet: "ApRnQN2HkbCn7W2WWiT2FEKvuKJp9LugRyAE1a9Hdz1" },
  { name: "FINN", twitter: "finnbags", wallet: "BTeqNydtKyDaSxQNRm8ByaUDPK3cpQ1FsXMtaF1Hfaom" },
  { name: "dash", twitter: "dashcrypto_", wallet: "4ESzFZUWUdr2GsgHBVeQKuzAmBWS5sRSaXw6PZH2EAau" },
  { name: "bilo", twitter: "chargememan", wallet: "7sA5em1nTKmLvGm8H85cpgA9hM9YvCoPp729mwe6akhh" },
  { name: "Mike", twitter: "mike8pump", wallet: "A8i6J8B1DgVdQaoeyrCmc18473EzYocEtZGavHT4sXzw" },
  { name: "rise_crypt", twitter: "rise_crypt", wallet: "AUEQxhkAVz71w2WBa9BYSoZrydhYNJaKmfNomoNs9E4t" },
  { name: "Cooker", twitter: "CookerFlips", wallet: "8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6" },
  { name: "Preston", twitter: "prestonharty", wallet: "HmtAZQn7U75jkAxrXNh8vRFCmjGjM3Q2WpiTHXoCJrUz" },
  { name: "Pikalosi", twitter: "pikalosi", wallet: "9cdZg6xR4c9kZiqKSzqjn4QHCXNQuC9HEWBzzMJ3mzqw" },
  { name: "Inquixit", twitter: "inquixit", wallet: "3L8RAxLkvwkz4CgHivaVRtq19741FAdGLk5DgjRfc1fW" },
  { name: "Thesis ✍️", twitter: "Theeesis", wallet: "5S9qzJhSooakBaA9qZT6vWtoSy8FvyfxJ4t1vXvEK9G7" },
  { name: "Zil", twitter: "zilxbt", wallet: "FSAmbD6jm6SZZQadSJeC1paX3oTtAiY9hTx1UYzVoXqj" },
  { name: "Meechie", twitter: "973Meech", wallet: "9iaawVBEsFG35PSwd4PahwT8fYNQe9XYuRdWm872dUqY" },
  { name: "wizard", twitter: "w1zar9", wallet: "DwCp9GZw3ueoXPykHSPUkRZEwcTVbJH2i9Sf1cXYicWf" },
  { name: "Boomer", twitter: "boomerbuilds", wallet: "4JyenL2p8eQZAQuRS8QAASy7TzEcqAeKGha6bhiJXudh" },
  { name: "Toxic weast", twitter: "Toxic_weast", wallet: "DU323DieHUGPmYamp6A4Ai1V4YSYgRi35mGpzJGrjf7k" },
  { name: "bruce", twitter: "onchainscammer", wallet: "4xHGhy4r41XNEgeHpKSC725aZjy6tR5E92xNjs4odBPR" },
  { name: "Paper", twitter: "stackppr", wallet: "FwjYcbfktK8PC2bzCrqxR6QkUPxmHFbcFGNrz3YAV7ft" },
  { name: "CookDoc", twitter: "CookDoc1993", wallet: "Dvbv5TdAyPpJk16X9mUxWFVicYtCUxTLhuof8TGuUaRv" },
  { name: "peacefuldestroy", twitter: "peacefuldestroy", wallet: "8AtQ4ka3dgtrH1z4Uq3Tm4YdMN3cK5RRj1eKuGNnvenm" },
  { name: "Numer0 (trench/arc)", twitter: "Numerooo0", wallet: "A3W8psibkTUvjxs4LRscbnjux6TFDXdvD4m4GsGpQ2KJ" },
  { name: "J Spizzle", twitter: "JSpizzleCrypto", wallet: "4z3WtX32eehkmnaNNstZWyAuVBhj6cgpk5JtkdTa4m4A" },
  { name: "Alpha wallet 4", twitter: "quarsays", wallet: "6pa2QnW2mB1F41FkytTYd2gTh9aTUCmdTGEgcFRXcQ8g" },
  { name: "Idontpaytaxes", twitter: "untaxxable", wallet: "2T5NgDDidkvhJQg8AHDi74uCFwgp25pYFMRZXBaCUNBH" },
  { name: "Bottom Seller", twitter: "bottomseller", wallet: "BtUBxH7bEjmDJbgVLxjEK7ZX72XPeDKaeXFufXnGATna" },
  { name: "fl0wjoe", twitter: "fl0wjoe", wallet: "9v9Xsxxu2pi4cDkTHtyL1Rg417uga48R2VcCP4L1Pe9R" },
  { name: "Rem", twitter: "yeaitsrem", wallet: "3pfqebV65sHMbF5z86HsPKSiTxwpNhCzjK5X7GUqCbtK" },
  { name: "Fozzy", twitter: "fozzycapone", wallet: "B9oKseVKRntTvfADyaUoH7oVmoyVbBfUf4NKyQc4KK2D" },
  { name: "Joji", twitter: "metaversejoji", wallet: "525LueqAyZJueCoiisfWy6nyh4MTvmF4X9jSqi6efXJT" },
  { name: "Ataberk 🧙‍♂️", twitter: "ataberk", wallet: "6hcX7fVMzeRpW3d7XhFsxYw2CuePfgSMmouZxSiNLj1U" },
  { name: "big bags bobby", twitter: "bigbagsbobby", wallet: "8oQoMhfBQnRspn7QtNAq2aPThRE4q94kLSTwaaFQvRgs" },
  { name: "Rasta", twitter: "rastacowboy2021", wallet: "RaSSH7hMwLKtMT96xZyY4JwHRCCNYvvNeBh6AaFMqdA" },
  { name: "jester", twitter: "thejester", wallet: "4s2WzRLa35FB58bZY1i4CN3WoywJeuYrGYHnTKFsT23z" },
  { name: "gr3g", twitter: "gr3gor14n", wallet: "J23qr98GjGJJqKq9CBEnyRhHbmkaVxtTJNNxKu597wsA" },
  { name: "Mak", twitter: "MakXBT", wallet: "3SU8wjyKGsKZWdxVfak6gkApBqZ8twP613HDGc8Httzr" },
  { name: "Jookiaus", twitter: "JookCrypto", wallet: "jsjsxPQQ8xoHvQ7ezhKiKWD8FnZe9txuRw3ewKRZUsb" },
  { name: "Hash", twitter: "Hashbergers", wallet: "DNsh1UfJdxmze6T6GV9QK5SoFm7HsM5TRNxVuwVgo8Zj" },
  { name: "OGAntD", twitter: "0GAntD", wallet: "215nhcAHjQQGgwpQSJQ7zR26etbjjtVdW74NLzwEgQjP" },
  { name: "Walta", twitter: "Walta61", wallet: "39q2g5tTQn9n7KnuapzwS2smSx3NGYqBoea11tBjsGEt" },
  { name: "Solana degen", twitter: "Solanadegen", wallet: "9tY7u1HgEt2RDcxym3RJ9sfvT3aZStiiUwXd44X9RUr8" },
  { name: "tech", twitter: "technoviking46", wallet: "5d3jQcuUvsuHyZkhdp78FFqc7WogrzZpTtec1X9VNkuE" },
  { name: "Classic", twitter: "simplyclassic69", wallet: "DsqRyTUh1R37asYcVf1KdX4CNnz5DKEFmnXvgT4NfTPE" },
  { name: "Cowboy🔶BNB", twitter: "feibo03", wallet: "6EDaVsS6enYgJ81tmhEkiKFcb4HuzPUVFZeom6PHUqN3" },
  { name: "dxrnelljcl", twitter: "dxrnell", wallet: "3jzHjoPKaceZjA6AqAWka7Ghw9F3w9k9cvjGTmybdioT" },
  { name: "set", twitter: "Setuhx", wallet: "62N1K57D37AUDGp68tnDYKPjGDsaAAtmo357nBtEtuR" },
  { name: "EvansOfWeb", twitter: "EvansOfWeb3", wallet: "5RQEcWJZdhkxRMbwjSq32RaocgYPaWDhi3ztimWUcrwo" },
  { name: "Marcell", twitter: "MarcellxMarcell", wallet: "FixmSpsBa7ew26gWdiqpoMAgKRFgbSXFbGAgfMZw67X" },
  { name: "bihoz", twitter: "bihozNFTs", wallet: "An68XCxJvfXc9NRWjNXGSFY55dyFVKjfgtpt8AKGJ2dE" },
  { name: "slingoor", twitter: "slingoorio", wallet: "6mWEJG9LoRdto8TwTdZxmnJpkXpTsEerizcGiCNZvzXd" },
  { name: "Danny", twitter: "0xSevere", wallet: "9FNz4MjPUmnJqTf6yEDbL1D4SsHVh7uA8zRHhR5K138r" },
  { name: "Megz 🦉", twitter: "DeltaXtc", wallet: "CECN4BW4DKnbyddkd9FhWVR5dotzKhQr5p7DUPhQ55Du" },
  { name: "Inside Calls", twitter: "insidecalls", wallet: "4NtyFqqRzvHWsTmJZoT26H9xtL7asWGTxpcpCxiKax9a" },
  { name: "narc", twitter: "narracanz", wallet: "CxgPWvH2GoEDENELne2XKAR2z2Fr4shG2uaeyqZceGve" },
  { name: "mercy", twitter: "mercularx", wallet: "F5jWYuiDLTiaLYa54D88YbpXgEsA6NKHzWy4SN4bMYjt" },
  { name: "Hueno", twitter: "HuenoZ", wallet: "FWAmTVsmAjxYZe4Nt5ooLDg6AHHUx3ST3nz89oGSGu59" },
  { name: "Sebi", twitter: "limpcritisism", wallet: "DxwDRWxQXDaVZquH3YvCVBQ75nUf16FttQ4q88okn5mc" },
  { name: "orangie", twitter: "orangie", wallet: "DuQabFqdC9eeBULVa7TTdZYxe8vK8ct5DZr4Xcf7docy" },
  { name: "dints", twitter: "dintsfi", wallet: "DbRQjQDTTsiBXg1TJdb55WvEr3JvqUyu4iJJ684Aqeu3" },
  { name: "Jay", twitter: "BitBoyJay", wallet: "HwRnKq7RPtKHvX9wyHsc1zvfHtGjPQa5tyZtGtbvfXE" },
  { name: "Keano", twitter: "nftkeano", wallet: "Ez2jp3rwXUbaTx7XwiHGaWVgTPFdzJoSg8TopqbxfaJN" },
  { name: "Eddy 💹🧲", twitter: "EddyMetaX", wallet: "DuGezKLZp8UL2aQMHthoUibEC7WSbpNiKFJLTtK1QHjx" },
  { name: "Phineas.SOL", twitter: "Phineas_Sol", wallet: "64ymeD9XTAkNJgHtXgrG6JCNZmBC9fSVcmgkL54pFikE" },
  { name: "Woozy", twitter: "woozy2so", wallet: "9tRff7L6Mx3ZDNBoGPffdjD3c9JNzLc3nxzadYH4TnAp" },
  { name: "zeropnl", twitter: "im0pnl", wallet: "4xY9T1Q7foJzJsJ6YZDSsfp9zkzeZsXnxd45SixduMmr" },
  { name: "Damian Prosalendis", twitter: "DamianProsa", wallet: "AEeJUPCiGR3yCoukTh1G58o4LYsUEyzrXtfmfMc2kJMX" },
  { name: "Latuche", twitter: "Latuche95", wallet: "GJA1HEbxGnqBhBifH9uQauzXSB53to5rhDrzmKxhSU65" },
  { name: "Zef", twitter: "zefwashere", wallet: "EjtQrPTbcMevStBkpnjsH23NfUCMhGHusTYsHuGVQZp2" },
  { name: "Dusty", twitter: "guidustyy", wallet: "B799XD2RtgkxYRvv5Q9CFnSpVifrsJErWz6MpvBdYFdR" },
  { name: "psykø", twitter: "psykogem", wallet: "FC3nyVqdufVfrgXiRJEqgST1JdJSEBEz6a9KoBfFP7c4" },
  { name: "Heyitsyolo", twitter: "Heyitsyolotv", wallet: "Av3xWHJ5EsoLZag6pr7LKbrGgLRTaykXomDD5kBhL9YQ" },
  { name: "Beaver", twitter: "beaverd", wallet: "GM7Hrz2bDq33ezMtL6KGidSWZXMWgZ6qBuugkb5H8NvN" },
  { name: "Hugo Fartingale", twitter: "HugoMartingale", wallet: "Au1GUWfcadx7jMzhsg6gHGUgViYJrnPfL1vbdqnvLK4i" },
  { name: "saale", twitter: "saale", wallet: "SAALE2x3sn51EyahJyqD6913L3GqHZdZo3egUdMayQp" },
  { name: "Mayhem Bot", twitter: "pumpfun", wallet: "BwWK17cbHxwWBKZkUYvzxLcNQ1YVyaFezduWbtm2de6s" },
  { name: "Cupsey", twitter: "Cupseyy", wallet: "2fg5QD1eD7rzNNCsvnhmXFm5hqNgwTTG8p7kQ6f3rx6f" },
  { name: "milito", twitter: "fnmilito", wallet: "EeXvxkcGqMDZeTaVeawzxm9mbzZwqDUMmfG3bF7uzumH" },
  { name: "bandit", twitter: "bandeez", wallet: "5B79fMkcFeRTiwm7ehsZsFiKsC7m7n1Bgv9yLxPp9q2X" },
  { name: "Limfork.eth", twitter: "Limfork", wallet: "BQVz7fQ1WsQmSTMY3umdPEPPTm1sdcBcX9sP7o6kPRmB" },
  { name: "^1s1mple", twitter: "s1mple_s1mple", wallet: "AeLaMjzxErZt4drbWVWvcxpVyo8p94xu5vrg41eZPFe3" },
  { name: "Domy", twitter: "domyxbt", wallet: "3LUfv2u5yzsDtUzPdsSJ7ygPBuqwfycMkjpNreRR2Yww" },
  { name: "jamessmith", twitter: "luckedhub", wallet: "EQaxqKT3N981QBmdSUGNzAGK5S26zUwAdRHhBCgn87zD" },
  { name: "Hesi", twitter: "hesikillaz", wallet: "FpD6n8gfoZNxyAN6QqNH4TFQdV9vZEgcv5W4H2YL8k4X" },
  { name: "cap", twitter: "himothy", wallet: "CAPn1yH4oSywsxGU456jfgTrSSUidf9jgeAnHceNUJdw" },
  { name: "Donuttcrypto", twitter: "donuttcrypto", wallet: "3wjyaSegfV7SZzjv9Ut1p6AcY5ZdoZjmu6i6QPCVvnmz" },
  { name: "Trey", twitter: "treysocial", wallet: "831yhv67QpKqLBJjbmw2xoDUeeFHGUx8RnuRj9imeoEs" },
  { name: "matsu", twitter: "matsu_sol", wallet: "9f5ywdCDA4QhSktBomozpHmZfSLqS6J9VqCrRehYWh1p" },
  { name: "Nyhrox", twitter: "nyhrox", wallet: "6S8GezkxYUfZy9JPtYnanbcZTMB87Wjt1qx3c6ELajKC" },
  { name: "Ban", twitter: "Bancrypto__", wallet: "8DGbkGgQewL9mx4aXzZCUChr7hBVXvPK9fYqSqc7Ajpn" },
  { name: "Setsu", twitter: "Setsu2k", wallet: "2k7Mnf2K3GhpB7hEVN1CFFeV4oNzzuCS5Q6SmcfAoLHd" },
  { name: "Leck", twitter: "LeckSol", wallet: "98T65wcMEjoNLDTJszBHGZEX75QRe8QaANXokv4yw3Mp" },
  { name: "Zyaf", twitter: "0xZyaf", wallet: "F5TjPySiUJMdvqMZHnPP85Rc1vErDGV5FR5P2vdVm429" },
  { name: "Ethan Prosper", twitter: "pr6spr", wallet: "sAdNbe1cKNMDqDsa4npB3TfL62T14uAo2MsUQfLvzLT" },
  { name: "Art", twitter: "ArtCryptoz", wallet: "CgaA9a1JwAXJyfHuvZ7VW8YfTVRkdiT5mjBBSKcg7Rz5" },
  { name: "Yenni", twitter: "Yennii56", wallet: "5B52w1ZW9tuwUduueP5J7HXz5AcGfruGoX6YoAudvyxG" },
  { name: "omar", twitter: "maghrrebi", wallet: "Dgehc8YMv6dHsiPJVoumvq4pSBkMVvrTgTUg7wdcYJPJ" },
  { name: "Loopierr", twitter: "Loopierr", wallet: "9yYya3F5EJoLnBNKW6z4bZvyQytMXzDcpU5D6yYr4jqL" },
  { name: "xunle", twitter: "xunle111", wallet: "4YzpSZpxDdjNf3unjkCtdWEsz2FL5mok7e5XQaDNqry8" },
  { name: "Netti", twitter: "Netti_kun", wallet: "8WN7tkp8WcZEYX2cSXJQY8u3q5QHEtykrZqJmFP7NYcf" },
  { name: "juicyfruity", twitter: "juicyfruityy2", wallet: "Cv4JVc25RZ7JV8HhEXrnxJjzebMBCqN5prB5ec43aJSz" },
];
